import { Navbar } from '@/components/navbar';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} p-4`}>
        <div className="flex flex-col overflow-hidden h-full gap-8 max-w-7xl mx-auto ">
          <Navbar />
          <div className=" h-full"> {children}</div>
        </div>
      </body>
    </html>
  );
}
